### PR TITLE
added PDF's, added titles to messages, update SVGs

### PR DESCRIPTION
**Pull request by rasummer**
@jroper can you take one last look at this and review my latest additions. I've added updated SVGs and PDFs, as well as add titles to some of the message files. I've been testing it locally and everything looks good to me! I'm happy to merge, just wanted an extra set of eyes on it.

thanks

Rich

### CODE REVIEW

**Comment by jroper** [comment]
Looks good.

You know... we could internationalise the SVG graphics themselves you wanted - as long as it's only the text that changes between translations.

**Comment by rasummer** [comment]
The SVGs also use different positioning numbers for the text. So for now I'd recommend we merge and get these live. I can start a new branch with some other UI upgrades that I want to do, and can add the SVGs to that list. Sound Good?

**Comment by rasummer** [comment]
@jroper I think we can push live now. Could you take a quick look at my additional changes I made to your work, and then merge and push live when you have a chance. thanks Rich.

**Comment by rasummer** [comment]
@jroper thanks, I see it's live.

**Pull request merged**
