### PR TITLE
Added Portuguese Brazilian Translation

### PR DESCRIPTION
**Pull request by rasummer**
@jroper 

Hey James, can you take a quick look at this PR. This is the first new language I've added to the new setup.  If all looks good, please merge and push live. 

best

Rich

### CODE REVIEW

**Comment by jroper** [comment]
Looks good, I'll just tweak the regex for language matching to be a little stricter.

**Comment by rasummer** [comment]
Thanks James

**Comment by jroper** [comment]
I also updated the code from `pt-br` to `pt-BR`, [RFC 5646](https://tools.ietf.org/html/rfc5646) says that they are case insensitive so both are ok, but it does define and recommend a standard for formatting to aid in communication.  This also fixed the link to the text only version, which uses `pt-BR` in the file name.

**Comment by jroper** [comment]
And it's deployed.

**Comment by rasummer** [comment]
Thank you sir. I'll let Jonas know ;)

Richard Summerhayes
*Creative Technologist, Typesafe, Inc.*
richard.summerhayes@typesafe.com
M: +1 415.637.0410
@richsummerhayes <https://twitter.com/richsummerhayes>

<http://event.scaladays.org/scaladays-amsterdam-2015>

**Pull request merged**
